/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["http://localhost:3000/r/utils.json","http://localhost:3000/r/themes/testing.json"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "colors": {
    name: "colors",
    description: "",
    type: "registry:style",
    registryDependencies: undefined,
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "themes/default": {
    name: "themes/default",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "themes/dirk": {
    name: "themes/dirk",
    description: "",
    type: "registry:theme",
    registryDependencies: ["http://localhost:3000/r/themes/default.json"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "src/registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "examples/button-demo": {
    name: "examples/button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["http://localhost:3000/r/button.json"],
    files: [{
      path: "src/registry/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }