import { type Registry } from 'shadcn/registry'
import 'dotenv/config'
const URL = String(process.env.APP_URL)

export const themes: Registry['items'] = [
  {
    name: 'themes/default',
    type: 'registry:theme',
    files: [],
    cssVars: {
      light: {
        radius: '0rem',
        background: '#ffffff' /* --color-mspa-700 */,
        foreground: '#000000',
        main: '#535353',
        'main-foreground': '#ffffff',
        card: '#eeeeee' /* --color-mspa-100 */,
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#9a9a9a' /* --color-mspa-500 */,
        'primary-foreground': '#000000',
        secondary: '#e0e0e0' /* --color-mspa-200 */,
        'secondary-foreground': '#000000',
        destructive: '#ff0000' /* --color-sburb-alpha */,
        'destructive-foreground': '#ffffff',
        muted: '#eeeeee' /* --color-mspa-100 */,
        'muted-foreground': '#535353' /* --color-mspa-700 */,
        accent: '#4ce24e' /* --color-sburb-beta */,
        'accent-foreground': '#ffffff',
        border: '#c6c6c6' /* --color-mspa-300 */,
        input: '#9a9a9a' /* --color-mspa-500 */,
        ring: '#4ce24e' /* --color-sburb-beta */,
        'toast-outline': '#c6c6c6' /* --color-mspa-300 */,
        'toast-border': '#b8b8b8' /* --color-mspa-400 */,
        sidebar: '#535353' /* --color-mspa-700 */,
        'sidebar-foreground': '#ffffff',
      },
      dark: {
        background: '#000000',
        foreground: '#ffffff',
        main: '#000000',
        'main-foreground': '#ffffff',
        card: '#323232' /* --color-mspa-900 */,
        'card-foreground': '#ffffff',
        popover: '#000000',
        'popover-foreground': '#ffffff',
        primary: '#b8b8b8' /* --color-mspa-400 */,
        'primary-foreground': '#ffffff',
        secondary: '#535353' /* --color-mspa-700 */,
        'secondary-foreground': '#ffffff',
        destructive: '#ff0000' /* --color-sburb-alpha */,
        'destructive-foreground': '#ffffff',
        muted: '#535353' /* --color-mspa-700 */,
        'muted-foreground': '#c6c6c6' /* --color-mspa-300 */,
        accent: '#900fff' /* --color-sgrub */,
        'accent-foreground': '#eeeeee' /* --color-mspa-100 */,
        border: '#9a9a9a' /* --color-mspa-500 */,
        input: '#9a9a9a' /* --color-mspa-500 */,
        ring: '#900fff' /* --color-sgrub */,
        'toast-outline': '#9a9a9a' /* --color-mspa-500 */,
        'toast-border': '#535353' /* --color-mspa-700 */,
        sidebar: '#000000',
        'sidebar-foreground': '#ffffff',
      },
      theme: {
        'breakpoint-sm': '450px',
        'breakpoint-md': '650px',
        'breakpoint-lg': '950px',
        'breakpoint-xl': '1280px',
        'breakpoint-2xl': '1920px',
        'container-3xs': '200px',
        'container-2xs': '325px',
        'container-xs': '450px',
        'container-sm': '525px',
        'container-md': '575px',
        'container-lg': '650px',
        'container-xl': '775px',
        'container-2xl': '850px',
        'container-3xl': '900px',
        'container-4xl': '950px',
        'container-5xl': '1000px',
        'container-6xl': '1050px',
        'container-7xl': '1080px',
        'container-prose': '65ch',
        'radius-2xs': 'calc(var(--radius) * 0.25)',
        'radius-xs': 'calc(var(--radius) * 0.5)',
        'radius-sm': 'calc(var(--radius) * 0.75)',
        'radius-base': 'var(--radius)',
        'radius-lg': 'calc(var(--radius) * 1.25)',
        'radius-xl': 'calc(var(--radius) * 1.5)',
        'radius-max': 'calc(var(--radius) * Infinity)',
        'font-sans': "'Verdana', sans-serif",
        'font-serif': "'Adobe Garamond Pro', serif",
        'font-mono': "'Courier New', monospace",
        'font-adobe-garamond-pro': "'Adobe Garamond Pro', serif",
        'font-homestuck': "'Homestuck', monospace",
        'color-primary-border':
          'color-mix(in oklch, var(--primary) 100%, var(--foreground) 50% )',
        'color-secondary-border':
          'color-mix(in oklch, var(--secondary) 100%, var(--foreground) 50% )',
        'color-destructive-border':
          'color-mix(in oklch, var(--destructive) 100%, var(--foreground) 50% )',
        'shadow-extrude-base':
          'calc(1px * var(--extrude-x)) calc(1px * var(--extrude-y)) 0px var(--tw-shadow-color, rgb(0 0 0 / 1)), calc(2px * var(--extrude-x)) calc(2px * var(--extrude-y)) 0px var(--tw-shadow-color, rgb(0 0 0 / 1))',
      },
    },
  },
  {
    name: 'themes/dirk',
    type: 'registry:theme',
    files: [],
    registryDependencies: [`${URL}/r/themes/default.json`],
    css: {
      '[data-theme="dirk"]': {
        '--accent': '#f2a400' /* --color-dirk */,
        '--ring': '#f2a400' /* --color-dirk */,
      },
    },
  },
  /* {
    name: 'themes/testing',
    type: 'registry:item',
    files: [
      {
        path: 'styles/colors.css',
        type: 'registry:file',
        target: 'styles/colors.css',
      },
    ],
    css: {
      "@import './colors.css'": {},
    },
  }, */
]
