import { type Registry } from 'shadcn/registry'

export const themes: Registry['items'] = [
  {
    name: 'theme-default',
    type: 'registry:theme',
    cssVars: {
      light: {
        radius: '0rem',
        foreground: 'oklch(from black)',
        background: 'oklch(from var(--color-mspa-700))',
        main: 'oklch(from white)',
        'main-foreground': 'oklch(from black)',
        card: 'oklch(from var(--color-mspa-100))',
        'card-foreground': 'oklch(from black)',
        popover: 'oklch(from white)',
        'popover-foreground': 'oklch(from black)',
        primary: 'oklch(from var(--color-sburb-beta))',
        'primary-foreground': 'oklch(from white)',
        secondary: 'oklch(var(--color-mspa-400))',
        'secondary-foreground': 'oklch(white)',
        destructive: 'oklch(var(--color-sburb-alpha))',
        'destructive-foreground': 'oklch(white)',
        muted: 'oklch(var(--color-mspa-300))',
        'muted-foreground': 'oklch(var(--color-mspa-700))',
        accent: 'oklch(var(--color-mspa-300))',
        'accent-foreground': 'oklch(var(--color-mspa-900))',
        border: 'oklch(var(--color-mspa-500))',
        input: 'oklch(var(--color-mspa-500))',
        ring: 'oklch(var(--color-sburb-beta))',
        'toast-outline': 'oklch(var(--color-mspa-300))',
        'toast-border': 'oklch(var(--color-mspa-400))',
        sidebar: 'oklch(from var(--color-mspa-700))',
        'sidebar-foreground': 'oklch(from white)',
        /*   sidebar-primary: oklch(0.205 0 0),
  sidebar-primary-foreground: oklch(0.985 0 0),
  sidebar-accent: oklch(0.97 0 0),
  sidebar-accent-foreground: oklch(0.205 0 0),
  sidebar-border: oklch(0.922 0 0),
  sidebar-ring: oklch(0.708 0 0), */
      },
      dark: {
        background: 'oklch(from black)',
        foreground: 'oklch(from white)',
        main: 'oklch(from var(--color-mspa-800))',
        'main-foreground': 'oklch(from white)',
        card: 'oklch(from var(--color-mspa-900))',
        'card-foreground': 'oklch(from white)',
        popover: 'oklch(from black)',
        'popover-foreground': 'oklch(from white)',
        primary: 'oklch(from var(--color-sgrub))',
        'primary-foreground': 'oklch(from white)',
        secondary: 'oklch(from var(--color-mspa-700))',
        'secondary-foreground': 'oklch(from white)',
        destructive: 'oklch(from var(--color-sburb-alpha))',
        'destructive-foreground': 'oklch(from white)',
        muted: 'oklch(from var(--color-mspa-700))',
        'muted-foreground': 'oklch(from var(--color-mspa-300))',
        accent: 'oklch(from var(--color-mspa-800))',
        'accent-foreground': 'oklch(from var(--color-mspa-100))',
        border: 'oklch(from var(--color-mspa-500))',
        input: 'oklch(from var(--color-mspa-500))',
        ring: 'oklch(from var(--color-sgrub))',
        'toast-outline': 'oklch(from var(--color-mspa-500))',
        'toast-border': 'oklch(from var(--color-mspa-700))',
        sidebar: 'oklch(from black)',
        'sidebar-foreground': 'oklch(from white)',
      },
      theme: {
        'extrude-x': '1',
        'extrude-y': '1',
      },
    },
  },
  {
    name: 'theme-dirk',
    type: 'registry:theme',
    css: {
      '[data-theme="dirk"]': {
        '--primary': 'var(--color-dirk)',
        '--ring': 'var(--color-dirk)',
      },
    },
  },
  {
    name: 'theme-dark',
    type: 'registry:theme',
    cssVars: {
      dark: {
        background: 'oklch(from black)',
        foreground: 'oklch(from white)',
        main: 'oklch(from var(--color-mspa-800))',
        'main-foreground': 'oklch(from white)',
        card: 'oklch(from var(--color-mspa-900))',
        'card-foreground': 'oklch(from white)',
        popover: 'oklch(from black)',
        'popover-foreground': 'oklch(from white)',
        primary: 'oklch(from var(--color-sgrub))',
        'primary-foreground': 'oklch(from white)',
        secondary: 'oklch(from var(--color-mspa-700))',
        'secondary-foreground': 'oklch(from white)',
        destructive: 'oklch(from var(--color-sburb-alpha))',
        'destructive-foreground': 'oklch(from white)',
        muted: 'oklch(from var(--color-mspa-700))',
        'muted-foreground': 'oklch(from var(--color-mspa-300))',
        accent: 'oklch(from var(--color-mspa-800))',
        'accent-foreground': 'oklch(from var(--color-mspa-100))',
        border: 'oklch(from var(--color-mspa-500))',
        input: 'oklch(from var(--color-mspa-500))',
        ring: 'oklch(from var(--color-sgrub))',
        'toast-outline': 'oklch(from var(--color-mspa-500))',
        'toast-border': 'oklch(from var(--color-mspa-700))',
      },
    },
  },
]
